name: Microservices CI - Run Tests and Deploy to CBH Cloud

on:
  push:
    branches:
      - main

jobs:
  node-tests:
    name: Image Service (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: medical_records_image_service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'
      - run: rm -rf node_modules && npm install
      - run: chmod +x node_modules/.bin/jest
      - run: npx jest

  user-service-tests:
    name: User Service (Spring Boot)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: medical_records_user_service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
      - run: bash ./mvnw test

  records-service-tests:
    name: Records Service (Spring Boot)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: medical_records_records_service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
      - run: bash ./mvnw test

  message-service-tests:
    name: Message Service (Spring Boot)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: medical_records_message_service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
      - run: bash ./mvnw test

  search-service-tests:
    name: Search Service (Quarkus)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: medical_records_search_service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
      - run: bash ./mvnw test

  build-and-push:
    name: Build and Push Docker Images to CBH Cloud
    runs-on: ubuntu-latest
    needs:
      - node-tests
      - user-service-tests
      - records-service-tests
      - message-service-tests
      - search-service-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # === FRONTEND ===
      - name: Login to CBH (Frontend)
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_FRONT }}
          password: ${{ secrets.DOCKER_PASSWORD_FRONT }}

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_TAG_FRONT }} ./medical_records_front
          docker push ${{ secrets.DOCKER_TAG_FRONT }}

      # === IMAGE SERVICE ===
      - name: Login to CBH (Image)
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_IMAGE }}
          password: ${{ secrets.DOCKER_PASSWORD_IMAGE }}

      - name: Build & Push Image Service
        run: |
          docker build -t ${{ secrets.DOCKER_TAG_IMAGE }} ./medical_records_image_service
          docker push ${{ secrets.DOCKER_TAG_IMAGE }}

      # === USER SERVICE ===
      - name: Login to CBH (User)
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_USER }}
          password: ${{ secrets.DOCKER_PASSWORD_USER }}

      - name: Build & Push User Service
        run: |
          docker build -t ${{ secrets.DOCKER_TAG_USER }} ./medical_records_user_service
          docker push ${{ secrets.DOCKER_TAG_USER }}

      # === RECORDS SERVICE ===
      - name: Login to CBH (Records)
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_RECORDS }}
          password: ${{ secrets.DOCKER_PASSWORD_RECORDS }}

      - name: Build & Push Records Service
        run: |
          docker build -t ${{ secrets.DOCKER_TAG_RECORDS }} ./medical_records_records_service
          docker push ${{ secrets.DOCKER_TAG_RECORDS }}

      # === MESSAGE SERVICE ===
      - name: Login to CBH (Message)
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_MESSAGE }}
          password: ${{ secrets.DOCKER_PASSWORD_MESSAGE }}

      - name: Build & Push Message Service
        run: |
          docker build -t ${{ secrets.DOCKER_TAG_MESSAGE }} ./medical_records_message_service
          docker push ${{ secrets.DOCKER_TAG_MESSAGE }}

      # === SEARCH SERVICE ===
      - name: Login to CBH (Search)
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_SEARCH }}
          password: ${{ secrets.DOCKER_PASSWORD_SEARCH }}

      - name: Build & Push Search Service
        run: |
          docker build -t ${{ secrets.DOCKER_TAG_SEARCH }} ./medical_records_search_service
          docker push ${{ secrets.DOCKER_TAG_SEARCH }}
